#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;

$root = $kobieta {female} | $mężczyzna {male};

$kobieta = kobieta | dziewczyna | dziewczynka | loszka | baba | babka | facetka;

$mężczyzna = mężczyzna | chłopak | chłopczyk | chłopiec | facet | men;