#ABNF 1.0;
language pl-pl;
mode voice;
root $root;
tag-format <semantics/1.0-literals>;

$root = [$zyczenie] [$czasownik] $rzeczownik1 {1} | [$zyczenie] [$czasownik] $rzeczownik2 {2} | [$zaimek] [$zyczenie] [$czasownik] $rzeczownik3 {3} | [$zyczenie] $czasownik4 [$spójnik4] [$rzeczownik4] {4};

$zyczenie = chciałbym | chciałabym | chcę;
$czasownik = policzyć | obliczyć | liczenie;

$rzeczownik1 = kalorii | kalorie;

$rzeczownik2 = bmi | beemi | bijemaj;

$rzeczownik3 = [dzienne] zapotrzebowanie [kaloryczne];

$czasownik4 = wyjście | wyjść | wychodzić | egzit | opuścić;
$rzeczownik4 = program | programu;
$spójnik4 = z;

$zaimek = moje | twoje;